name: Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install pytest-cov

    - name: Run tests with coverage
      run: |
        pytest tests/ --ignore=tests/integration \
          --cov=nextgen_kernels_api \
          --cov-report=term-missing \
          --cov-report=xml \
          --cov-report=html \
          -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: htmlcov/
